---
- name: Deploy to K8
  hosts: localhost
  tasks: 
   - name: Create k8 Namespace
     k8s:
      name: my-app
      api_version: v1
      kind: Namespace
      state: present
      
   - name: Deploy nginx app
     k8s:
      src: /home/ubuntu/nginx.yaml
      state: present
      namespace: my-app

      
